# dependency-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-service
  namespace: dependency-ns  # In separate namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependency-service
  template:
    metadata:
      labels:
        app: dependency-service
    spec:
      containers:
      - name: dependency
        image: dependency-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: dependency-service
  namespace: dependency-ns
spec:
  selector:
    app: dependency-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP