# main-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-medium-test
  namespace: default  # Explicitly in default namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-medium-test
  template:
    metadata:
      labels:
        app: sre-medium-test
    spec:
      containers:
      - name: main-app
        image: sre-medium-test:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_MODE
          value: "flaky"
        - name: DEPENDENCY_URL
          value: "http://dependency-service.dependency-ns.svc.cluster.local:8081"  # Cross-namespace DNS
        - name: HEALTH_CHECK_FAIL_RATE
          value: "0.2"
        volumeMounts:
        - name: health-volume
          mountPath: /health
        livenessProbe:
          exec:
            command: ["cat", "/health/status"]
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: log-sidecar
        image: busybox:latest
        command: ["sh", "-c", "tail -f /logs/app.log"]
        volumeMounts:
        - name: log-volume
          mountPath: /logs
      volumes:
      - name: health-volume
        emptyDir: {}
      - name: log-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sre-medium-test-service
  namespace: default
spec:
  selector:
    app: sre-medium-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP