name: Debug Kubernetes Issues

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to deploy to"
        required: false
        default: "troubleshooting"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Kubernetes cluster
        run: |
         mkdir -p ~/.kube
         echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
         kubectl get pods -A
          

      - name: Run Kubernetes Troubleshooting Action
        uses: becloudready/k8s-interview-action@v2
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: "troubleshooting"
          failure_mode: "oom"
