name: Debug Kubernetes Issues

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Namespace to deploy to"
        required: false
        default: "troubleshooting"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Kubernetes cluster
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

  

      - name: Run Kubernetes Troubleshooting Action
        uses: becloudready/k8s-interview-action@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ github.event.inputs.namespace || 'troubleshooting' }}
  
